
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - core.core.gardener.cloud
  resources:
  - dhcpentries
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - core.core.gardener.cloud
  resources:
  - dhcpentries/finalizers
  verbs:
  - update
- apiGroups:
  - core.core.gardener.cloud
  resources:
  - dhcpentries/status
  verbs:
  - get
  - patch
  - update
